import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  scrollView: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 16,
    paddingTop: 60, // Add top padding for transparent header
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 20,
    color: "#1a1a1a",
    textAlign: "center",
  },
  note: {
    color: "#666",
    fontSize: 16,
    textAlign: "center",
    marginTop: 20,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
    color: "#1a1a1a",
  },
  cardText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#4a4a4a",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  ratingText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#4a4a4a",
  },
  ratingBadge: {
    backgroundColor: "#007AFF",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ratingValue: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 8,
  },
  statItem: {
    alignItems: "center",
    width: "48%",
    marginBottom: 12,
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#007AFF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
  },
  chip: {
    backgroundColor: "#e9ecef",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  chipText: {
    fontSize: 12,
    color: "#495057",
    fontWeight: "500",
  },
  weatherCard: {
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#E0E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  weatherHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  weatherIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  weatherEmoji: {
    fontSize: 36,
  },
  weatherMainInfo: {
    flex: 1,
  },
  weatherTemp: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  weatherConditions: {
    fontSize: 15,
    color: "#555",
    fontWeight: "600",
    textTransform: "capitalize",
  },
  weatherDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0E8F0",
  },
  weatherDetailItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  weatherDetailIcon: {
    fontSize: 20,
  },
  weatherDetailText: {
    fontSize: 15,
    color: "#4a4a4a",
    fontWeight: "600",
    marginLeft: 4,
  },
  recommendationsList: {
    gap: 8,
  },
  recommendationItem: {
    fontSize: 14,
    lineHeight: 20,
    color: "#4a4a4a",
  },
  dayContainer: {
    backgroundColor: "#f8f9fa",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  dayTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    color: "#1a1a1a",
  },
  dayStats: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 8,
  },
  dayStat: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  dayDescription: {
    fontSize: 15,
    color: "#2c3e50",
    lineHeight: 24,
    marginTop: 12,
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#007AFF",
    fontWeight: "400",
    letterSpacing: 0.2,
  },
  physicalGeographyContainer: {
    marginTop: 16,
    padding: 14,
    backgroundColor: "#f0f7ff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#b8d4f0",
  },
  physicalGeographyTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1a5490",
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  physicalGeographyText: {
    fontSize: 15,
    color: "#2c3e50",
    lineHeight: 24,
    letterSpacing: 0.2,
    fontWeight: "400",
  },
  warningCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#ff6b6b",
    backgroundColor: "#fff5f5",
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#d63031",
    marginBottom: 8,
  },
  warningText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#e17055",
  },
  analyzePrimaryButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginVertical: 12,
  },
  analyzePrimaryButtonDisabled: {
    opacity: 0.6,
  },
  analyzePrimaryText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  progressContainer: {
    paddingHorizontal: 4,
    marginTop: 8,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#e9ecef",
    borderRadius: 6,
    overflow: "hidden",
  },
  progressFill: {
    height: 8,
    backgroundColor: "#007AFF",
  },
  progressText: {
    marginTop: 6,
    textAlign: "center",
    color: "#666",
    fontSize: 12,
  },
  pickerModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  pickerModalCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    margin: 20,
    minWidth: 320,
    maxWidth: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  pickerModalTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 12,
    textAlign: "center",
    color: "#333",
  },
  pickerContainerBox: {
    alignItems: "center",
    marginBottom: 20,
    minHeight: 100,
    justifyContent: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 10,
  },
  pickerCancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e1e5e9",
    alignItems: "center",
  },
  pickerCancelText: {
    color: "#666",
    fontSize: 16,
    fontWeight: "500",
  },
  pickerOkButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#007AFF",
    alignItems: "center",
  },
  pickerOkText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  dateInput: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e1e5e9",
    backgroundColor: "#fff",
  },
  pickerInlineContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    padding: 12,
  },
  pickerInlineCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    elevation: 10,
  },
});
