import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  map: {
    flex: 1,
  },
  error: {
    textAlign: "center",
    marginTop: 40,
    color: "#d00",
  },
  searchToggleButton: {
    position: "absolute",
    top: 66,
    right: 30,
    zIndex: 1001,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 20,
    padding: 10,
    elevation: 6,
  },
  infoButtonLeft: {
    position: "absolute",
    left: 30,
    bottom: 100,
    zIndex: 2000,
    backgroundColor: "rgba(0,0,0,0.75)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
  },
  infoButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  routeMenuButton: {
    position: "absolute",
    left: 30,
    bottom: 160,
    zIndex: 2000,
    backgroundColor: "rgba(0,0,0,0.75)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
  },
  routeMenuModal: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    width: "90%",
    maxHeight: 600,
    alignSelf: "center",
    marginTop: "auto",
    marginBottom: "auto",
    justifyContent: "flex-start",
    overflow: "visible",
  },
  routeMenuHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  routeMenuTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
  },
  routeMenuCloseButton: {
    padding: 4,
  },
  routeMenuListWrapper: {
    height: 400,
    maxHeight: 400,
    overflow: "visible",
  },
  routeMenuList: {
    paddingBottom: 20,
  },
  routeMenuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    marginBottom: 8,
    overflow: "visible",
  },
  routeMenuItemActive: {
    backgroundColor: "#d0e8ff",
    borderWidth: 2,
    borderColor: "#007AFF",
  },
  routeMenuItemDragHandle: {
    marginRight: 12,
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  routeMenuItemContent: {
    flex: 1,
    marginRight: 12,
  },
  routeMenuItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  routeMenuItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  routeMenuItemInput: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    borderWidth: 1,
    borderColor: "#007AFF",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flex: 1,
  },
  routeMenuItemCoords: {
    fontSize: 12,
    color: "#666",
  },
  routeMenuItemActions: {
    flexDirection: "row",
    gap: 8,
  },
  routeMenuActionButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  menuContainer: {
    position: "absolute",
    bottom: 100,
    right: 30,
    zIndex: 1001,
    alignItems: "center",
    width: 44,
  },
  blurMenuContainer: {
    borderRadius: 30,
    padding: 12,
    overflow: "hidden",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  routeControlsContainer: {
    flexDirection: "column",
    gap: 8,
  },
  menuToggleButton: {
    backgroundColor: "rgba(0,0,0,0.75)",
    borderRadius: 22,
    padding: 12,
    elevation: 8,
  },
  menuToggleButtonActive: {
    backgroundColor: "#007AFF",
  },
  routeModeButton: {
    backgroundColor: "rgba(0,0,0,0.6)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  routeModeButtonActive: {
    backgroundColor: "#007AFF",
  },
  roadRoutingButton: {
    backgroundColor: "rgba(0,0,0,0.6)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  roadRoutingButtonActive: {
    backgroundColor: "#34C759",
  },
  routingIndicatorContainer: {
    position: "absolute",
    top: 120,
    right: 30,
    zIndex: 1002,
  },
  infoButton: {
    position: "absolute",
    right: 30,
    bottom: 100,
    zIndex: 2000,
    backgroundColor: "rgba(0,0,0,0.75)",
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 10,
    elevation: 8,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
    color: "#1a1a1a",
  },
  modalContent: {
    gap: 16,
  },
  formGroup: {
    gap: 8,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  formInput: {
    borderWidth: 1,
    borderColor: "#e1e5e9",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: "#f8f9fa",
  },
  formInputFocused: {
    borderColor: "#007AFF",
    backgroundColor: "#fff",
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#e1e5e9",
    borderRadius: 12,
    backgroundColor: "#f8f9fa",
  },
  picker: {
    height: 50,
  },
  dateRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e1e5e9",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: "#f8f9fa",
  },
  elevationSummary: {
    backgroundColor: "#f0f8ff",
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  elevationText: {
    fontSize: 14,
    color: "#333",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    gap: 12,
  },
  cancelButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e1e5e9",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 16,
    fontWeight: "500",
  },
  analyzePrimaryButton: {
    backgroundColor: "#007AFF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    maxWidth: 200,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  analyzePrimaryText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  analyzePrimaryButtonDisabled: {
    opacity: 0.6,
    shadowOpacity: 0.1,
  },
  progressContainer: {
    marginTop: 16,
    gap: 8,
  },
  progressBar: {
    height: 6,
    backgroundColor: "#e1e5e9",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#007AFF",
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  infoModalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    maxHeight: "85%",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  infoModalTitle: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
    color: "#1a1a1a",
  },
  infoSection: {
    marginBottom: 16,
  },
  infoSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  infoLabel: {
    fontSize: 14,
    color: "#666",
  },
  infoValue: {
    fontSize: 14,
    fontWeight: "500",
    color: "#333",
  },
  coordinatesToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    marginTop: 8,
  },
  coordinatesToggleText: {
    fontSize: 14,
    color: "#007AFF",
    fontWeight: "500",
  },
  coordinatesList: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    gap: 4,
  },
  coordinateItem: {
    fontSize: 12,
    color: "#666",
    fontFamily: "monospace",
  },
  distanceMarkerContainer: {
    backgroundColor: "rgba(0, 122, 255, 0.9)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  distanceMarkerText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
});
